// Generated by CoffeeScript 1.4.0
(function() {

  (function() {
    var _this = this;
    this.compile = this.render;
    return this.__express = function(filename, options, cb) {
      try {
        return cb(null, _this.render);
      } catch (err) {
        return cb(err);
      }
    };
  }).call(module.exports = require('doT'));

}).call(this);
